sytem:
  username: ceshi
  password: ceshi
email:
  from: 1@.com
  to: 2@.com
dataSource:
  master:
    dataType: mysql
    url: 127.0.0.1
    port: 3306
    dbName: javatest
    username: root
    password: huan
mylogger:
  console:
    level: debug
    
    